// Origin OvO CopyRight Reserved

#pragma once

#include "NativeGameplayTags.h"

/**
 * 
 */
namespace FPSGameplayTags
{
	/** Input Tags **/
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload_Rifle);
	
	/** Player Tags **/
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_DryFire_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_AimFire_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Aim_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Reload_Rifle);

	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Rifle);

	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Rifle);
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Bullet_Hit);

	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Aim);  //  Ãé×¼×´Ì¬

	/** Shared Tags **/
	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);

	FPSGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
}